version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/:cached
            - ./docker/site.conf:/etc/nginx/conf.d/site.conf
            - ./docker/ca.crt:/etc/nginx/keys/ca.crt
            - ./docker/ca.key:/etc/nginx/keys/ca.key
        links:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                - user=${USER}
        volumes:
            - ./:/var/www/html/:cached
        user: ${USER}
        links:
          - mailhog
    mailhog:
          image: mailhog/mailhog
          ports:
            - "8025:8025"
            - "1025:1025"